name: Update TinaCMS Dependencies
on:
  push:
    branches:
      - dependabot/npm_and_yarn/**

jobs:
  update-tinacms:
    runs-on: ubuntu-latest
    steps:
      # Clone repo
      - name: Check out repo to update
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      # Install deps, update Tina packages, update schema
      - name: Install dependencies
        run: pnpm install
      - name: Update Tina packages
        run: pnpm update tinacms@latest @tinacms/cli@latest
      - name: Update Schema
        run: pnpm tinacms audit
      # Commit changes
      - name: Commit changes back to branch
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update TinaCMS generated files"
          branch: ${{ github.ref }}
          committer_name: GitHub Actions
          committer_email: actions@github.com
